/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bibliotecas`; params?: Router.UnknownInputParams; } | { pathname: `/cloudinary`; params?: Router.UnknownInputParams; } | { pathname: `/contato`; params?: Router.UnknownInputParams; } | { pathname: `/emailseatendimento`; params?: Router.UnknownInputParams; } | { pathname: `/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/inicialrota`; params?: Router.UnknownInputParams; } | { pathname: `/manualdoaluno`; params?: Router.UnknownInputParams; } | { pathname: `/muraldosestudantes`; params?: Router.UnknownInputParams; } | { pathname: `/murallogin`; params?: Router.UnknownInputParams; } | { pathname: `/plataformaserecursos`; params?: Router.UnknownInputParams; } | { pathname: `/queroseraluno`; params?: Router.UnknownInputParams; } | { pathname: `/redefinirsenhamural`; params?: Router.UnknownInputParams; } | { pathname: `/sou_aluno`; params?: Router.UnknownInputParams; } | { pathname: `/uploadImageToCloudinary`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bibliotecas`; params?: Router.UnknownOutputParams; } | { pathname: `/cloudinary`; params?: Router.UnknownOutputParams; } | { pathname: `/contato`; params?: Router.UnknownOutputParams; } | { pathname: `/emailseatendimento`; params?: Router.UnknownOutputParams; } | { pathname: `/firebase`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/inicialrota`; params?: Router.UnknownOutputParams; } | { pathname: `/manualdoaluno`; params?: Router.UnknownOutputParams; } | { pathname: `/muraldosestudantes`; params?: Router.UnknownOutputParams; } | { pathname: `/murallogin`; params?: Router.UnknownOutputParams; } | { pathname: `/plataformaserecursos`; params?: Router.UnknownOutputParams; } | { pathname: `/queroseraluno`; params?: Router.UnknownOutputParams; } | { pathname: `/redefinirsenhamural`; params?: Router.UnknownOutputParams; } | { pathname: `/sou_aluno`; params?: Router.UnknownOutputParams; } | { pathname: `/uploadImageToCloudinary`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/bibliotecas${`?${string}` | `#${string}` | ''}` | `/cloudinary${`?${string}` | `#${string}` | ''}` | `/contato${`?${string}` | `#${string}` | ''}` | `/emailseatendimento${`?${string}` | `#${string}` | ''}` | `/firebase${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/inicialrota${`?${string}` | `#${string}` | ''}` | `/manualdoaluno${`?${string}` | `#${string}` | ''}` | `/muraldosestudantes${`?${string}` | `#${string}` | ''}` | `/murallogin${`?${string}` | `#${string}` | ''}` | `/plataformaserecursos${`?${string}` | `#${string}` | ''}` | `/queroseraluno${`?${string}` | `#${string}` | ''}` | `/redefinirsenhamural${`?${string}` | `#${string}` | ''}` | `/sou_aluno${`?${string}` | `#${string}` | ''}` | `/uploadImageToCloudinary${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bibliotecas`; params?: Router.UnknownInputParams; } | { pathname: `/cloudinary`; params?: Router.UnknownInputParams; } | { pathname: `/contato`; params?: Router.UnknownInputParams; } | { pathname: `/emailseatendimento`; params?: Router.UnknownInputParams; } | { pathname: `/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/inicialrota`; params?: Router.UnknownInputParams; } | { pathname: `/manualdoaluno`; params?: Router.UnknownInputParams; } | { pathname: `/muraldosestudantes`; params?: Router.UnknownInputParams; } | { pathname: `/murallogin`; params?: Router.UnknownInputParams; } | { pathname: `/plataformaserecursos`; params?: Router.UnknownInputParams; } | { pathname: `/queroseraluno`; params?: Router.UnknownInputParams; } | { pathname: `/redefinirsenhamural`; params?: Router.UnknownInputParams; } | { pathname: `/sou_aluno`; params?: Router.UnknownInputParams; } | { pathname: `/uploadImageToCloudinary`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
